version: '2'
services:
  printed-app:
    image: printed
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://printed-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=Printed
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  printed-mongodb:
    extends:
      file: mongodb.yml
      service: printed-mongodb
