version: '2'
services:
  jhipster_printed-app:
    image: jhipster_printed
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://jhipster_printed-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=jhipster_printed
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipster_printed-mongodb:
    extends:
      file: mongodb.yml
      service: jhipster_printed-mongodb
